<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>BDVM.Web</AssemblyName>
    <RootNamespace>BDVM.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BDVM.Common\BDVM.Common.csproj" />
    <ProjectReference Include="..\BDVM.Core\BDVM.Core.csproj" />
  </ItemGroup>
</Project>
